---
title: "Effects of AirBnb on NY"
subtitle: "How AirBnb shapes living pattern in NYC!"
author: "Ranjitha, Rahul, Anand, Shivendra "
date: "1 May 2018"
output: ioslides_presentation
---


```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path="images/",
               cache.path="cache/",
               cache=FALSE,
               echo=FALSE,
               message=FALSE,
               warning=FALSE) 
```

# Introduction  
  
## Identify commercial vs household airbnb listings.

## Distribution of commercial and household listings across NY.

## Distribution of commercial and household listings by room type.


## Comparitive analysis between commercial and household listings wrt user scores.

## Comparitive analysis between commercial and household listings wrt user reviews.

## Comparitive analysis between commercial and household listings wrt price.

## Rental Policy Change

## Effects of Policy Change in distribution of room types

## Effects of Policy Change on commercial listings

## Effects of Policy Change on non-commercial listings

## Impact of Policy Change on distribution of room types

## Pointout users having multiple listings

## Compare quality between commercial and non-commercial

## How have AirBnb's growth affected rental prices?

