---
title: "Reviews"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tm)
library(tidytext)
library(wordcloud)
library(plotly)
library(plotrix)
```


```{r}
total_listings <- read.csv("data/total_listings.csv")
total_listings <- read.csv("data/total_listings.csv")
total_listings_non_commercial <- read.csv("data/total_listings_non_commercial.csv")

jan_reviews <- read.csv("data/jan_reviews.csv")
feb_reviews <- read.csv("data/feb_reviews.csv")
```



```{r}
total_listings$avg_review_value <- (( total_listings$review_scores_cleanliness + total_listings$reviews_per_month + total_listings$review_scores_accuracy + total_listings$review_scores_checkin + total_listings$review_scores_communication + total_listings$review_scores_location )/6)
```

```{r}
# avg reviews are ranging from 2-10
# classifying 2- as low
# 5-8 as medium
# 8+ as high 
# then comparing commercial and non-commercial based on type of review
total_listings <- total_listings %>% mutate(review_quality = if_else(avg_review_value<=6, "LOW", if_else(avg_review_value>6 & avg_review_value<=8, "MEDIUM", if_else(avg_review_value>8, "HIGH", ""))))

```


```{r}
reviews_gp = group_by(total_listings,is_commercial, review_quality)
reviews_sm = summarise(reviews_gp,count=n())
colnames(reviews_sm) = c("Listing_Type","review_quality","Count")


reviews_count = summarise(group_by(total_listings,is_commercial), count=n())
colnames(reviews_count) = c("Listing_Type","Count")

review_percentage <- merge(reviews_sm, reviews_count, by='Listing_Type')
review_percentage$Count.x <- (review_percentage$Count.x * 100 )/ review_percentage$Count.y
```


```{r}

x <- unique(review_percentage$review_quality)
y <- filter(review_percentage, Listing_Type == "Commercial Listing")$Count.x
y2 <- filter(review_percentage, Listing_Type == "Household Listing")$Count.x
text <- c('27% market share', '24% market share', '19% market share')
data <- data.frame(x, y, y2, text)

data
p <- data %>% 
  plot_ly() %>%
add_trace(name="Commercial Listing", x = ~x, y = ~y, type = 'bar', 
             marker = list(color = 'rgb(158,202,225)',
                           line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
  add_trace(name="Household Listing",x = ~x, y = ~y2, type = 'bar', 
            marker = list(color = 'rgb(58,200,225)',
                          line = list(color = 'rgb(8,48,107)', width = 1.5))) %>%
layout(title = "Average Reviews",
         barmode = 'group',
         xaxis = list(title = "Type"),
         yaxis = list(title = "Score"))
p
```


```{r}
removeNumPunct <- function(x){gsub("[^[:alpha:][:space:]]*", "", x)}
removeCaps <- function(x){gsub("[A-Z]+\b", "", x)}

clean_corpus <- function(corpus){
  corpus <- tm_map(corpus, content_transformer(removeCaps))
  corpus <- tm_map(corpus, content_transformer(tolower))
  corpus <- tm_map(corpus, removeWords, c(stopwords("en")))  
    # We could add more stop words as above
  corpus <- tm_map(corpus, removeNumbers)
  corpus <- tm_map(corpus, content_transformer(removeNumPunct))
  corpus <- tm_map(corpus, stripWhitespace)
  return(corpus)
}


clean_and_get_top_terms <- function(data){
  data <- data.frame(text=data$comments, doc_id=row.names(data), stringsAsFactors=FALSE)
  df_source <- DataframeSource(data)
  corpus <- VCorpus(df_source)
  

  corpus <- clean_corpus(corpus)
  corpus_stemmed <- tm_map(corpus, stemDocument)
  corpus <- as.VCorpus(corpus_stemmed)
  corpus_dtm <- tidy(DocumentTermMatrix(corpus, control = list(weighting = weightTfIdf)))
  
  
  data <- corpus_dtm %>%     group_by(term) %>%
                summarise(n = sum(count)) %>%
                top_n(n = 50, wt = n)  %>%
                mutate(term = reorder(term, n))
  
  return(data)
}

```

```{r}

df <- subset(merge(total_listings, jan_reviews, by.x="id", by.y="listing_id"), select=c("is_commercial", "comments", "id"))
df$comments <- gsub("[^\x20-\x7E]", "", df$comments)

df_not_commercial <- filter(df, is_commercial == "Household Listing")
df_commercial <- filter(df, is_commercial == "Commercial Listing")

df_commercial <- df_commercial[!duplicated(df_commercial[,c('id')]),]
df_not_commercial <- head(df_not_commercial[!duplicated(df_not_commercial[,c('id')]),], nrow(df_commercial))


not_commercial_terms <- clean_and_get_top_terms(df_not_commercial)
commercial_terms <- clean_and_get_top_terms(df_commercial)
```


```{r}
not_commercial_terms$unsuccess_term_freq <- not_commercial_terms$n
commercial_terms$success_term_freq <- commercial_terms$n
common_terms <- merge(commercial_terms, not_commercial_terms, by="term")
p <- pyramid.plot(common_terms$success_term_freq, common_terms$unsuccess_term_freq, 
                  labels = common_terms$term, 
             gap = 20, 
             top.labels = c("Household", " ", "Commercial"), 
             main = "Words in Common", 
             laxlab = NULL, 
             raxlab = NULL, 
             unit = NULL, 
             labelcex=0.5)



```

